all : flash

TARGET:=nav_lcd
CH32V003FUN=../ch32v003fun/ch32v003fun
MINICHLINK=../ch32v003fun/minichlink
#LINKER_SCRIPT=./ch32v003fun.ld

include $(CH32V003FUN)/ch32v003fun.mk

flash : cv_flash
clean : cv_clean

